server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: admin123
  environment:
    - SERVER_PORT=8081
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
