spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: true
logging:
  level:
    liquibase: DEBUG


